### ISSUE TITLE
erorr when login  and reuqest password , maybe karena pindah server minsoo? 

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/partbook#2]
![Screen Shot 2022-10-28 at 13 32 29](https://user-images.githubusercontent.com/96053043/198527021-96840cdf-286a-4319-935f-778f2e085914.png)

**Comment by 1ocate** [comment]
<img width="534" alt="Screen Shot 2022-10-28 at 8 28 32 PM" src="https://user-images.githubusercontent.com/29521447/198577015-1fe3e40d-6fdc-4c7a-8ccc-76b17e245f7c.png">

udah bisa

**Comment by kevinsunjaya** [comment]
thanks minsoo
